require('core.opt')
require('core.keymap')

require('plugins.lualine')
require('plugins.packer')
--require('plugins.treesitter')
--require('plugins.lsp')
--require('plugins.cmp')
require('plugins.coc')
require('plugins.c_f_c_p')
